INSERT INTO rss2tlg_feed_config (id, name, url, language, category, enabled) VALUES 
(1, 'Hacker News', 'https://hnrss.org/frontpage', 'en', 'technology', 1),
(2, 'TechCrunch', 'https://techcrunch.com/feed/', 'en', 'technology', 1),
(3, 'Wired', 'https://www.wired.com/feed/rss', 'en', 'technology', 1),
(4, 'Ars Technica', 'https://feeds.arstechnica.com/arstechnica/index', 'en', 'technology', 1),
(5, 'The Verge', 'https://www.theverge.com/rss/index.xml', 'en', 'technology', 1),
(6, 'BBC Technology', 'https://feeds.bbci.co.uk/news/technology/rss.xml', 'en', 'technology', 1),
(7, 'Le Monde Informatique', 'https://www.lemondeinformatique.fr/flux-rss/actualites', 'fr', 'technology', 1),
(8, 'Les Numeriques', 'https://www.lesnumeriques.com/actualite/high-tech.rss', 'fr', 'technology', 1),
(9, '01net', 'https://www.01net.com/rss/actualites/high-tech/', 'fr', 'technology', 1),
(10, 'ZDNet France', 'https://www.zdnet.fr/news/rss.xml', 'fr', 'technology', 1),
(11, 'Clubic', 'https://www.clubic.com/feed/rss', 'fr', 'technology', 1),
(12, 'Le Figaro Tech', 'https://www.lefigaro.fr/secteur/high-tech/rss.xml', 'fr', 'technology', 1),
(13, 'Heise Online', 'https://www.heise.de/rss/heise-top-atom.xml', 'de', 'technology', 1),
(14, 'Golem.de', 'https://rss.golem.de/rss.php?feed=RSS2.0', 'de', 'technology', 1),
(15, 't3n', 'https://t3n.de/feed', 'de', 'technology', 1),
(16, 'Chip.de', 'https://www.chip.de/rss/rss_rssnews.xml', 'de', 'technology', 1),
(17, 'ComputerBase', 'https://www.computerbase.de/rss/news.xml', 'de', 'technology', 1),
(18, 'Netzwelt', 'https://www.netzwelt.de/rss', 'de', 'technology', 1),
(19, '36Kr', 'https://36kr.com/feed', 'zh', 'technology', 1),
(20, 'TechNode Chinese', 'https://technode.com/feed/', 'zh', 'technology', 1),
(21, 'PingWest', 'https://www.pingwest.com/feed', 'zh', 'technology', 1),
(22, 'IFanr', 'https://www.ifanr.com/feed', 'zh', 'technology', 1),
(23, 'Leiphone', 'https://www.leiphone.com/feed', 'zh', 'technology', 1),
(24, 'CSDN', 'https://blog.csdn.net/rss/list', 'zh', 'technology', 1),
(25, 'Lenta.ru', 'https://lenta.ru/rss', 'ru', 'general', 1),
(26, 'RBC Technology', 'https://www.rbc.ru/rss/freenews/992.rss', 'ru', 'technology', 1),
(27, 'TJournal', 'https://tjournal.ru/rss', 'ru', 'technology', 1),
(28, 'Habr', 'https://habr.com/ru/rss/all/all/', 'ru', 'technology', 1),
(29, '3DNews', 'https://www.3dnews.ru/news/rss/', 'ru', 'technology', 1),
(30, 'iXBT', 'https://www.ixbt.com/news/rss.xml', 'ru', 'technology', 1);