/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19  Distrib 10.11.13-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: rss2tlg
-- ------------------------------------------------------
-- Server version	10.11.13-MariaDB-0ubuntu0.24.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `openrouter_metrics`
--

DROP TABLE IF EXISTS `openrouter_metrics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `openrouter_metrics` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор записи',
  `generation_id` varchar(255) DEFAULT NULL COMMENT 'Уникальный ID генерации от OpenRouter',
  `model` varchar(255) NOT NULL COMMENT 'Название модели (например, deepseek/deepseek-chat)',
  `provider_name` varchar(255) DEFAULT NULL COMMENT 'Провайдер модели (DeepInfra, Anthropic, Google)',
  `created_at` bigint(20) DEFAULT NULL COMMENT 'Unix timestamp создания запроса от OpenRouter',
  `generation_time` int(11) DEFAULT NULL COMMENT 'Время генерации ответа в мс',
  `latency` int(11) DEFAULT NULL COMMENT 'Общая задержка запроса в мс',
  `moderation_latency` int(11) DEFAULT NULL COMMENT 'Время модерации контента в мс',
  `tokens_prompt` int(11) DEFAULT NULL COMMENT 'Количество токенов в промпте (OpenRouter подсчет)',
  `tokens_completion` int(11) DEFAULT NULL COMMENT 'Количество токенов в ответе (OpenRouter подсчет)',
  `native_tokens_prompt` int(11) DEFAULT NULL COMMENT 'Токены промпта по подсчету провайдера',
  `native_tokens_completion` int(11) DEFAULT NULL COMMENT 'Токены ответа по подсчету провайдера',
  `native_tokens_cached` int(11) DEFAULT NULL COMMENT 'Закешированные токены (prompt caching)',
  `native_tokens_reasoning` int(11) DEFAULT NULL COMMENT 'Токены рассуждений (для reasoning моделей)',
  `usage_total` decimal(10,8) DEFAULT NULL COMMENT 'Общая стоимость запроса в USD',
  `usage_cache` decimal(10,8) DEFAULT NULL COMMENT 'Стоимость использования кеша в USD',
  `usage_data` decimal(10,8) DEFAULT NULL COMMENT 'Стоимость веб-поиска/data retrieval в USD',
  `usage_file` decimal(10,8) DEFAULT NULL COMMENT 'Стоимость обработки файлов в USD',
  `finish_reason` varchar(50) DEFAULT NULL COMMENT 'Причина завершения (stop, length, content_filter)',
  `pipeline_module` varchar(100) DEFAULT NULL COMMENT 'Модуль pipeline (Summarization, Deduplication, Translation)',
  `batch_id` int(11) DEFAULT NULL COMMENT 'ID batch обработки (если применимо)',
  `task_context` text DEFAULT NULL COMMENT 'Дополнительный контекст задачи (JSON)',
  `full_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Полный JSON ответ от OpenRouter для будущего анализа' CHECK (json_valid(`full_response`)),
  `recorded_at` timestamp NULL DEFAULT current_timestamp() COMMENT 'Время записи метрик в БД',
  PRIMARY KEY (`id`),
  KEY `idx_model` (`model`),
  KEY `idx_provider` (`provider_name`),
  KEY `idx_generation_id` (`generation_id`),
  KEY `idx_pipeline_module` (`pipeline_module`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_recorded_at` (`recorded_at`),
  KEY `idx_batch_id` (`batch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Детальные метрики OpenRouter API';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `openrouter_metrics`
--

LOCK TABLES `openrouter_metrics` WRITE;
/*!40000 ALTER TABLE `openrouter_metrics` DISABLE KEYS */;
INSERT INTO `openrouter_metrics` VALUES
(1,'gen-1762889098-ihx12JvQwJ16XbxY2baL','google/gemma-3-27b-it','Novita',1762889098,8875,694,NULL,3628,368,3628,368,0,0,0.00050028,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889098-ihx12JvQwJ16XbxY2baL\",\"provider\":\"Novita\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889098,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"```json\\n{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 42.5,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 20.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 10.0,\\n    \\\"temporal_gap_hours\\\": 0.16666666666666666,\\n    \\\"matched_entities\\\": [\\\"Россия\\\", \\\"Казахстан\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"The new article discusses the explanation for the fighter jet escort of the Kazakh President\'s plane, while the existing articles cover different topics: relations between Russia and Kazakhstan (Article 470), Hezbollah\'s stance on Israel (Article 473), and retail self-regulation in Russia (Article 472). While all articles share the same publication date, the core events and key facts are distinct. The entity overlap is limited to Russia and Kazakhstan, which is insufficient to consider it a duplicate. The similarity score of 42.5% reflects the shared date and countries but highlights the different events.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\\n```\",\"refusal\":null,\"reasoning\":null}}],\"system_fingerprint\":\"\",\"usage\":{\"prompt_tokens\":3628,\"completion_tokens\":368,\"total_tokens\":3996,\"prompt_tokens_details\":null,\"completion_tokens_details\":null}}','2025-11-11 19:25:09'),
(2,'gen-1762889110-KJC7QaJ4pfzEAG1MlaQ3','google/gemma-3-27b-it','DeepInfra',1762889110,7380,506,NULL,3628,373,3628,373,0,0,0.00038234,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889110-KJC7QaJ4pfzEAG1MlaQ3\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889110,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 65.0,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 60.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 40.0,\\n    \\\"temporal_gap_hours\\\": 0.16666666666666666,\\n    \\\"matched_entities\\\": [\\\"Касым-Жомарт Токаев\\\", \\\"Россия\\\", \\\"Казахстан\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"Both articles relate to the visit of Kazakhstan\'s President Tokayev to Russia and were published on the same day. However, they cover different aspects of the visit. Article 470 reports Tokayev\'s statement regarding the strong relationship between Kazakhstan and Russia, while Article 469 focuses on Peskov\'s explanation of the fighter jet escort. The core events are distinct: a diplomatic statement versus an explanation of protocol. The similarity score of 65% reflects the shared entities and timeframe, but the differing events and focus indicate it\'s an update or related story, not a duplicate.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3628,\"completion_tokens\":373,\"total_tokens\":4001,\"prompt_tokens_details\":null}}','2025-11-11 19:25:19'),
(3,'gen-1762889120-aJO6f2nMv4txJiw1qrvB','google/gemma-3-27b-it','DeepInfra',1762889120,6833,887,NULL,3086,327,3086,327,0,0,0.00032676,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889120-aJO6f2nMv4txJiw1qrvB\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889120,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 35.0,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 15.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 5.0,\\n    \\\"temporal_gap_hours\\\": 6,\\n    \\\"matched_entities\\\": [\\\"истребители\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"Both articles mention fighter jets (истребители) and were published on the same day. However, they describe completely different events. Article 471 reports on a building collapse, an attempted plane hijacking, and a soccer coach\'s dismissal. Article 469 focuses on the explanation for fighter jet escort of the Kazakh president\'s plane. The core events are unrelated, and the entity overlap is minimal. The similarity score of 35% reflects the shared date and the mention of fighter jets, but the overall content is distinct.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3086,\"completion_tokens\":327,\"total_tokens\":3413,\"prompt_tokens_details\":null}}','2025-11-11 19:25:28'),
(4,'gen-1762889197-FRjmSi4cMP7Dch29AnX0','google/gemma-3-27b-it','DeepInfra',1762889197,NULL,NULL,NULL,3628,351,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889197-FRjmSi4cMP7Dch29AnX0\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889197,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 42.5,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 40.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 10.0,\\n    \\\"temporal_gap_hours\\\": 0.16666666666666666,\\n    \\\"matched_entities\\\": [\\\"Касым-Жомарт Токаев\\\", \\\"Россия\\\", \\\"Казахстан\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"The new article discusses the explanation for the fighter jet escort of the Kazakh President\'s plane, while Article 470 focuses on a statement regarding the relationship between Russia and Kazakhstan. Both articles share entities like Kazakhstan and Russia, and were published on the same day. However, the core events are distinct: one is about a military escort protocol, and the other is about diplomatic relations. The fact overlap is minimal, limited to the publication date. Therefore, it is a related but different story.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3628,\"completion_tokens\":351,\"total_tokens\":3979,\"prompt_tokens_details\":null}}','2025-11-11 19:26:46'),
(5,'gen-1762889207-cS8U0TzjwX0SPNnFeghE','google/gemma-3-27b-it','DeepInfra',1762889207,NULL,NULL,NULL,3628,382,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889207-cS8U0TzjwX0SPNnFeghE\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889207,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 65.0,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 70.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 40.0,\\n    \\\"temporal_gap_hours\\\": 5,\\n    \\\"matched_entities\\\": [\\\"Касым-Жомарт Токаев\\\", \\\"Россия\\\", \\\"Казахстан\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true},\\n      {\\\"type\\\": \\\"location\\\", \\\"value\\\": \\\"Кремль\\\", \\\"matched\\\": true},\\n      {\\\"type\\\": \\\"statement\\\", \\\"value\\\": \\\"positive relations\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"Both articles relate to the visit of the Kazakh President to Russia. However, Article 469 focuses on the explanation of the fighter jet escort, while Article 470 reports on a statement made by Tokayev regarding the overall state of relations between Kazakhstan and Russia. While they share entities and the timeframe, the core events are distinct. The new article presents a statement about the lack of serious problems, while the existing article explains a specific incident. Therefore, it\'s an update related to the visit, but not a duplicate.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3628,\"completion_tokens\":382,\"total_tokens\":4010,\"prompt_tokens_details\":null}}','2025-11-11 19:26:56'),
(6,'gen-1762889217-vRutrEg1m5SkZ09pt7W0','google/gemma-3-27b-it','DeepInfra',1762889217,7968,1168,NULL,3086,338,3086,338,0,0,0.00032850,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889217-vRutrEg1m5SkZ09pt7W0\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889217,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 35.0,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 15.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 10.0,\\n    \\\"temporal_gap_hours\\\": 6,\\n    \\\"matched_entities\\\": [\\\"истребители\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"Both articles mention fighter jets (истребители) and were published on the same day. However, they describe completely different events. Article 471 reports on a building collapse in Krasnogorsk, an attempted hijacking of a Russian fighter jet by Ukrainian intelligence, and a football manager\'s dismissal. Article 469 concerns the explanation for Russian fighter jet escorting the Kazakh president\'s plane. The core events are unrelated, and the shared timeframe and mention of \'fighter jets\' are not enough to consider them duplicates. The similarity score of 35% reflects the minimal overlap.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3086,\"completion_tokens\":338,\"total_tokens\":3424,\"prompt_tokens_details\":null}}','2025-11-11 19:27:07'),
(7,'gen-1762889228-dTJfVN0MzAYlEqa0Xpon','google/gemma-3-27b-it','DeepInfra',1762889228,6238,621,NULL,3628,301,3628,301,0,0,0.00037093,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889228-dTJfVN0MzAYlEqa0Xpon\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889228,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 35.0,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 10.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 0.0,\\n    \\\"temporal_gap_hours\\\": 0,\\n    \\\"matched_entities\\\": [],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"The new article discusses a proposal by the Russian Ministry of Industry and Trade to create a self-regulatory body for retailers. The existing articles cover diplomatic relations between Kazakhstan and Russia, and a statement from Hezbollah. While all articles were published on the same day, they cover entirely different events and entities. There is minimal entity overlap (only a shared date) and no overlap in core events or key facts. Therefore, the new article is not a duplicate.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3628,\"completion_tokens\":301,\"total_tokens\":3929,\"prompt_tokens_details\":null}}','2025-11-11 19:27:16'),
(8,'gen-1762889236-JMrQSCLRK12sLq3L6xGe','google/gemma-3-27b-it','DeepInfra',1762889236,6463,484,NULL,3637,341,3637,341,0,0,0.00037807,NULL,NULL,NULL,'stop','DeduplicationService',NULL,NULL,'{\"id\":\"gen-1762889236-JMrQSCLRK12sLq3L6xGe\",\"provider\":\"DeepInfra\",\"model\":\"google\\/gemma-3-27b-it\",\"object\":\"chat.completion\",\"created\":1762889236,\"choices\":[{\"logprobs\":null,\"finish_reason\":\"stop\",\"native_finish_reason\":\"stop\",\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"{\\n  \\\"deduplication_status\\\": \\\"checked\\\",\\n  \\\"is_duplicate\\\": false,\\n  \\\"duplicate_of_item_id\\\": null,\\n  \\\"similarity_score\\\": 35.2,\\n  \\\"confidence\\\": 0.75,\\n  \\\"similarity_method\\\": \\\"ai_semantic\\\",\\n  \\\"analysis\\\": {\\n    \\\"entity_overlap\\\": 20.0,\\n    \\\"event_match\\\": false,\\n    \\\"fact_overlap\\\": 10.0,\\n    \\\"temporal_gap_hours\\\": 0.16666666666666666,\\n    \\\"matched_entities\\\": [\\\"Израиль\\\"],\\n    \\\"matched_events\\\": null,\\n    \\\"matched_facts\\\": [\\n      {\\\"type\\\": \\\"date\\\", \\\"value\\\": \\\"2025-11-11\\\", \\\"matched\\\": true}\\n    ]\\n  },\\n  \\\"reasoning\\\": \\\"The new article discusses a statement by the leader of Hezbollah regarding continued resistance against Israel. The existing articles cover topics such as a Kazakh president\'s visit to Russia, relations between Russia and Kazakhstan, and a proposal for retail self-regulation. While all articles were published on the same day, they cover completely different events and entities. The only overlap is the mention of Israel in the new article and a very limited temporal match. The core events are distinct, and there\'s minimal fact overlap. Therefore, it is not a duplicate.\\\",\\n  \\\"recommendation\\\": \\\"publish\\\",\\n  \\\"can_be_published\\\": true\\n}\",\"refusal\":null,\"reasoning\":null}}],\"usage\":{\"prompt_tokens\":3637,\"completion_tokens\":341,\"total_tokens\":3978,\"prompt_tokens_details\":null}}','2025-11-11 19:27:24');
/*!40000 ALTER TABLE `openrouter_metrics` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-11-11 19:28:24
